baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'october'

# Enable this for tailwind in markdown files
[markup.goldmark.renderer]
unsafe=true

# Add menu links to things from /content/ here (eg. markdown.md)

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1